<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYKHACHSAN_WEB" Class="KhachSanDBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.DICHVU" Member="DICHVUs">
    <Type Name="DICHVU">
      <Column Name="MADICHVU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENDICHVU" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DONVITINH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GIATHUEDICHVU" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MALOAIDICHVU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DICHVU_PHIEUSDDV" Member="PHIEUSDDVs" ThisKey="MADICHVU" OtherKey="MADICHVU" Type="PHIEUSDDV" />
      <Association Name="LOAIDICHVU_DICHVU" Member="LOAIDICHVU" ThisKey="MALOAIDICHVU" OtherKey="MALOAIDICHVU" Type="LOAIDICHVU" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CCCD" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Association Name="KHACHHANG_PHIEUDATPHONG" Member="PHIEUDATPHONGs" ThisKey="MAKH" OtherKey="MAKH" Type="PHIEUDATPHONG" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHOADON" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NGAYTHANHTOAN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MAPHIEUDATPHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANHANVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHIEUDATPHONG_HOADON" Member="PHIEUDATPHONG" ThisKey="MAPHIEUDATPHONG" OtherKey="MAPHIEUDATPHONG" Type="PHIEUDATPHONG" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIDICHVU" Member="LOAIDICHVUs">
    <Type Name="LOAIDICHVU">
      <Column Name="MALOAIDICHVU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENLOAIDICHVU" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="LOAIDICHVU_DICHVU" Member="DICHVUs" ThisKey="MALOAIDICHVU" OtherKey="MALOAIDICHVU" Type="DICHVU" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MALOAIPHONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENLOAIPHONG" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="GIATHUE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="LOAIPHONG_PHONG" Member="PHONGs" ThisKey="MALOAIPHONG" OtherKey="MALOAIPHONG" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANHANVIEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNHANVIEN" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="NAMSINH" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="HOADON" />
      <Association Name="NHANVIEN_PHIEUDATPHONG" Member="PHIEUDATPHONGs" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="PHIEUDATPHONG" />
      <Association Name="NHANVIEN_PHIEUSDDV" Member="PHIEUSDDVs" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="PHIEUSDDV" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="TAIKHOANs" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MAPHANQUYEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENPHANQUYEN" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="QUYENHAN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="PHANQUYEN_TAIKHOAN" Member="TAIKHOANs" ThisKey="MAPHANQUYEN" OtherKey="MAPHANQUYEN" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUDATPHONG" Member="PHIEUDATPHONGs">
    <Type Name="PHIEUDATPHONG">
      <Column Name="MAPHIEUDATPHONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SONGUOI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYNHANPHONG" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYTRADUKIEN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TIENCOC" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANHANVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUDATPHONG_HOADON" Member="HOADONs" ThisKey="MAPHIEUDATPHONG" OtherKey="MAPHIEUDATPHONG" Type="HOADON" />
      <Association Name="PHIEUDATPHONG_PHIEUSDDV" Member="PHIEUSDDVs" ThisKey="MAPHIEUDATPHONG" OtherKey="MAPHIEUDATPHONG" Type="PHIEUSDDV" />
      <Association Name="KHACHHANG_PHIEUDATPHONG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="NHANVIEN_PHIEUDATPHONG" Member="NHANVIEN" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="PHONG_PHIEUDATPHONG" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUSDDV" Member="PHIEUSDDVs">
    <Type Name="PHIEUSDDV">
      <Column Name="MAPHIEUSDDV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NGAYSUDUNG" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MADICHVU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAPHIEUDATPHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANHANVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUDATPHONG_PHIEUSDDV" Member="PHIEUDATPHONG" ThisKey="MAPHIEUDATPHONG" OtherKey="MAPHIEUDATPHONG" Type="PHIEUDATPHONG" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="DICHVU_PHIEUSDDV" Member="DICHVU" ThisKey="MADICHVU" OtherKey="MADICHVU" Type="DICHVU" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="NHANVIEN_PHIEUSDDV" Member="NHANVIEN" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MANHANVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAPHANQUYEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="NHANVIEN" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="PHANQUYEN_TAIKHOAN" Member="PHANQUYEN" ThisKey="MAPHANQUYEN" OtherKey="MAPHANQUYEN" Type="PHANQUYEN" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAPHONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SONGUOITOIDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="HINH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MALOAIPHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHONG_PHIEUDATPHONG" Member="PHIEUDATPHONGs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHIEUDATPHONG" />
      <Association Name="LOAIPHONG_PHONG" Member="LOAIPHONG" ThisKey="MALOAIPHONG" OtherKey="MALOAIPHONG" Type="LOAIPHONG" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>